echo "$(echo "grant select,insert,update(activo) on asignacion_ubicaciones_vehiculos to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select,insert,update(observacion) on desperfectos_vehiculos to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select,insert,update(ruta_imagen) on imagenes_desperfectos to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select,update(estado_usuario,conectado,ultima_conexion) on usuarios to $1" | dbaccess technosoft_db2)"

echo "$(echo "grant select,insert,update(incidente_vehiculo) on inspecciones to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select,update(estado_vehiculo,baja) on vehiculos to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select on estados_usuario to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select on roles_usuario to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select on estados_vehiculo to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select on tipos_ubicaciones to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select on tipos_vehiculo to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select,update(cantidad_vehiculos_actual) on ubicaciones to $1" | dbaccess technosoft_db2)"
echo "$(echo "grant select,update on vehiculos_lote to $1" | dbaccess technosoft_db2)"
